# Generated by Django 5.0.7 on 2026-07-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_player_phone_manual_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_players', to='academy.traininggroup'),
        ),
    ]
