# Generated by Django 5.0.7 on 2026-07-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_player_options_player_secondary_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
    ]
