# Generated by Django 5.0.7 on 2026-07-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_player_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='academy.traininggroup', verbose_name='Primary Group'),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_players', to='academy.traininggroup', verbose_name='Secondary Group'),
        ),
    ]
